spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lol_analyzer?useSSL=false&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver